2021-10-09T22:09:47.855967Z
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", 
line 589, in spawn_worker worker.init_process() File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", 
line 92, in init_process super().init_process() File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", 
line 134, in init_process self.load_wsgi() File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", 
line 146, in load_wsgi self.wsgi = self.app.wsgi() File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", 
line 67, in wsgi self.callable = self.load() File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", 
line 58, in load return self.load_wsgiapp() File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", 
line 48, in load_wsgiapp return util.import_app(self.app_uri) File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", 
line 359, in import_app mod = importlib.import_module(module) File "/usr/local/lib/python3.9/importlib/__init__.py", 
line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", 
line 1030, in _gcd_import File "<frozen importlib._bootstrap>", 
line 1007, in _find_and_load File "<frozen importlib._bootstrap>", 
line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", 
line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", 
line 850, in exec_module File "<frozen importlib._bootstrap>", 
line 228, in _call_with_frames_removed File "/app/main.py", 
line 15, in <module> import dialogue File "/app/dialogue.py", 
line 16, in <module> import model_management_engine as me File "/app/model_management_engine.py", 
line 16, in <module> import NLP_core_manager File "/app/NLP_core_manager.py", 
line 21, in <module> import NN_models as NN File "/app/NN_models.py", 
line 13, in <module> from keras_self_attention import SeqSelfAttention File "/usr/local/lib/python3.9/site-packages/keras_self_attention/__init__.py", 
line 1, in <module> from .seq_self_attention import SeqSelfAttention File "/usr/local/lib/python3.9/site-packages/keras_self_attention/seq_self_attention.py", 
line 1, in <module> from .backend import keras File "/usr/local/lib/python3.9/site-packages/keras_self_attention/backend.py", 
line 16, in <module> import keras File "/usr/local/lib/python3.9/site-packages/keras/__init__.py", 
line 25, in <module> from keras import models File "/usr/local/lib/python3.9/site-packages/keras/models.py", 
line 19, in <module> from keras import backend File "/usr/local/lib/python3.9/site-packages/keras/backend.py", 
line 285, in <module> tf.__internal__.register_clear_session_function(clear_session) AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'register_clear_session_function'